config/routes.rb
Rails.application.routes.draw do
  get 'surveys/index'

  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :surveys

  #home pages
  match '/about/' => 'home#about', :via => :get
  match '/help/' => 'home#help', :via => :get
  match '/examples/' => 'home#examples', :via => :get
  match '/legal/' => 'home#legal', :via => :get

  match '/:id' => 'surveys#take', :via => :get, :as => :take
  match '/:id' => 'surveys#respond', :via => :post
  match '/results/:id' => 'surveys#results', via: [:get, :post], :as => :results
  match '/admin/:id/close' => 'surveys#toggle', via: [:get, :post], :as => :closesurvey, :state => true
  match '/admin/:id/unclose' => 'surveys#toggle', via: [:get, :post], :as => :unclosesurvey, :state => false

  root :to => "home#index", :via => :get
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def about
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def help
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def examples
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def legal
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container">
  <div class="row panel panel-info">
      <div class="panel-heading">About Qwk.io</div>
        <div class="panel-body">
          Qwk.io is the quickest, easiest way to conduct surveys. If you just want to ask a bunch of people some questions and
          don’t need fancy templates or crosstabs, and don’t want to be re-billed $20/month until your great grandchildren get
          a notarized letter from the Canadian ambassador to Fiji, Qwk.io is the service for you.
        </div>
  </div>
</div>

app/views/home/examples.html.erb
<div class="container">
   <div class="panel panel-info">
      <div class="panel-heading">Example 1</div>
      <div class="panel-body">
<small><pre>
Customer Satisfaction: Qwk.io

Please answer the following questions based on your experience creating and publishing surveys using Qwk.io. If you've been using the system for a while, please focus on your most recent experiences (we're improving quickly!)

1) How many surveys have you published with Qwk.io?
___

2) What methods have you used to send your public link?
[ ] Email
[ ] Facebook
[ ] Twitter
[ ] Web page

3) On the whole, how happy are you with Qwk.io?
( ) Not at all
( ) Somewhat
( ) Very
( ) Super incredibly satisfied

4) Should we consider more elaborate question types?
[ ] Yes
[ ] No

6) Once we exit beta, would you be willing to pay $1 per survey for the service?
( ) Definitely not
( ) Maybe, but doubtful
( ) Not sure
( ) Probably
( ) Yes, yes, positively yes!

7) What thoughts do you have for how we could improve Qwk.io?
___
___
</pre></small>
      </div>
      <div class="panel-heading">Example 2</div>
      <div class="panel-body">
<small><pre>
Reunion Dinner

Hi, everyone! I can't believe it's already been 10 whole days since we graduated! I'm planning a reunion dinner and wanted to get your thoughts on where we should hold it. Please send this link to anyone not on the mailing list.

1) What type of food should we consider?
[ ] Burgers & Pub food
[ ] Chinese
[ ] French
[ ] Indian
[ ] Insects
[ ] Italian / Pizza
[ ] Thai
[ ] Vegetarian

2) How likely are you to attend if we do it Saturday the 21st?
( ) Can't make it
( ) Maybe, but doubtful
( ) Probably
( ) You betcha!

3) How likely are you to attend if we do it Saturday the 28th?
( ) Can't make it
( ) Maybe, but doubtful
( ) Probably
( ) You betcha!

4) Who should we draft for a speech?
( ) John
( ) Spence
( ) Molly
( ) Anyone but Spence

5) Are there any particular restaurants you'd like us to consider?
_____

6) Please list any dietary restrictions or other thoughts you have about the reunion dinner:
___
___
</pre></small>
      </div>
      <div class="panel-heading">Example 3</div>
      <div class="panel-body">
<small><pre>
Uniform Choice

Hello, Big League Leaguers! It's time for another year with your favorite co-ed Ultimate Frisbee team! After the complaints about the uniforms last year (I still don't see what's wrong with green and pink), I decided to do a quick survey to figure out how to best nattily attire our noble team this year. Please take a moment to let me know your thoughts; if you don't answer, you can't complain.

1) What should the primary uniform color be?
( ) Red
( ) Pink
( ) Mauve
( ) Purple
( ) Magenta
( ) Fuchsia

2) What color should the highlights be (collar, stripes, numbers)?
( ) Green
( ) Yellow
( ) Yellow-green
( ) Forest

3) What dates are you planning to attend?
[ ] April 3
[ ] April 10
[ ] April 17
[ ] April 23
[ ] April 24
[ ] May 1
[ ] May 8
[ ] May 11 (night)
[ ] May 18

4) Are you interested in being contacted to arrange carpools?
( ) Yes
( ) No

5) If so, please let me know who you are (otherwise the survey is anonymous)
___

6) Any other thoughts / suggestions?
___
___
</pre></small>
    </div>
  </div>
</div>

app/views/home/help.html.erb
<div class="container">
  <div class="row panel panel-info">
    <div class="panel-heading">Help</div>
    <div class="panel-body">
      <p>
        <ol>
          <li>Create your survey with the world’s simplest markup. It takes just a couple of minutes. It looks like a survey.</li>
          <li>You will get two links: a public link where people can take the survey, and a private link where you can view responses. Distribute the public link to people you would like to respond. Keep the private link secret, unless you want everyone to see all of the responses, in which case we’re fine if you send it out.</li>
          <li>The first time you view the results of your survey, it costs you a buck (US$1). That’s it. From then on, whenever you (or anyone else) views responses, it’s free. Payments are accepted via PayPal and are super easy, just like everything else here.</li>
        </ol>
      </p>
      </div>
  </div>
  <div class="row panel panel-info">
    <div class="panel-heading">Survey Advice</div>
    <div class="panel-body">We built Qwk.io because we needed something like it. So we’ve had some experience with surveys, and we’ve done things right and we’ve done things wrong. Here’s some general advice based on our experience:</p>
      <p>
        <ul>
          <li>Use number ranges in radio buttons rather than single line text to collect numeric responses. Odds are you’re going to want to group responses into ranges anyway, and it’s easier to process the results if people are selecting “six to ten” rather than writing in “7”, “nine”, “6”, and “eihgt” [sic].</li>
          <li>Arrange answers in a consistent manner. Either arrange answers alphabetically or in ascending numerical order, or arrange them by some other logical order like distance or month. But be consistant, as much as possible.</li>
          <li>Avoid leading questions or leading answers. If you find yourself writing “Don’t you think that…”, you’ve gone astray. Likewise, if your ratings are “Terrible”, “Poor”, “Fair”, “Good”, and “Excellent!!!!!!!”, you may be skewing your results.</li>
        </ul>
      </p>
    </div>
  </div>
  <div class="row panel panel-info">
    <div class="panel-heading">Markup</div>
    <div class="panel-body">
           <p>Qwk.io supports four basic question types: single choice, multiple choice, single line text, and multiple line text.</p>
           <div class="panel-body"><u>Single Choice</u></div>
           <p>When you want to ask a user to choose between two or more options, and only want one answer, single choice is the way to go. Qwk.io can render single choice questions as either a series of radio buttons or as a dropdown box. Both get you the same data, only the presentation is different.</p>
           <div class="panel-body"><u>Radio Buttons</u></div>
           <small><pre>
           ( ) Choice One
           ( ) Choice Two
           ( ) Choice Three
           </pre></small>

           <p>…and you can continue on from there to as many choices as you like.  It might not be a bad idea to include a <i>"None"</i> option as well, since radio buttons cannot be unchecked once they're selected. Qwk.io will never do this for you, since your survey is your business.</p>
           <p>But what if you don’t like the way it looks when there are 30 options to choose from, so the user might have to scroll back up to see the question by the time they’re read all the options? Well, that’s when to use a dropdown.</p>

           <div class="panel-body"><u>Dropdowns</u></div>
           <small><pre>
           < > Choice One
           < > Choice Two
           < > Choice Three
           </pre></small>

           <div class="panel-body"><u>Multiple Choice</u></div>
           <p>Multiple choice questions allow a user to pick zero or more answers from a predefined list. Qwk.io implements multiple choice questions as checkboxes; you can create them like this:</p>
           <small><pre>
           [ ] Choice 1
           [ ] Choice 2
           [ ] Choice 3
           </pre></small>

           <p>Note that users can select anywhere from zero to every choice listed; Qwk.io does not support requiring an answer or limiting a user to at most N answers (but hey, if that’s a feature you want, by all means let us know).</p>

           <div class="panel-body"><u>Single Line Text</u></div>
           <p>This is pretty self explanatory – if you want a user to write in a short response without having predefined options, the single line is for you. This is ideal for open ended number questions or questions where you’re pretty sure just a few words will suffice. You create single line text questions with three or more underscore characters, like this:</p>

           <small><pre>
           How many times have you used our service?
           ___
           </pre></small>

           <div class="panel-body">…or like this:</div>
           <small><pre>
           How many times have you used our service?
           _________________
           </pre></small>

           <div class="panel-body"><u>Multiple Line Text</u></div>
           <p>When you want to collect a response that’s likely to be longer than fits in a single line text, use the multiple line text (aka Textbox) answer type. It allows users to type arbitrarily long answers – they can write a book in that thing if they are so inclined. You can create a multiple line text answer by putting three underscores on two consecutive lines, like so:</p>

           <small><pre>
           What else could we do to improve the service?
           ___
           ___
           </pre></small>
         </div>
       </div>
   </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row text-center">
      <h1>Qwk.io!</h2>
      <p>"Create your survey in the world's easiest markup."</p>
    </div>
    <hr>
    <div class="row text-center">
      <div class="col-lg-offset-1 col-lg-2 col-md-offset-1 col-md-2  col-xs-offset-1 col-xs-5">
        <p>1. Create</p>
        <img src="/img/create.png">
      </div>
      <div class="col-lg-offset-1 col-lg-2 col-md-offset-1 col-md-2 col-xs-offset-1 col-xs-5">
        <p>2. URLs</p>
        <img src="/img/link.png">
      </div>
      <div class="col-lg-offset-1col-lg-2 col-md-offset-1 col-md-2 col-xs-offset-1 col-xs-5">
        <p>3. Take</p>
        <img src="/img/take.png">
      </div>
      <div class="col-lg-offset-1 col-lg-2 col-md-offset-1 col-md-2 col-xs-offset-1 col-xs-5">
        <p>4. Result</p>
        <img src="/img/result.png">
      </div>
    </div>
    <hr>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-offset-1 col-md-5  panel panel-info">
      <div class="row panel-heading">Step 1: Create</div>
      <div class="row panel-body">Create your survey in markup and submit.</div>
      <%= form_tag(surveys_url) do %>
      <textarea class="form-control" name="survey" rows="22" wrap="soft">
Enter your survey title here
Any text you enter here will display below the title.
1) Example multiple choice question
[ ] One
[ ] Two
[ ] Three
2) Example radio list question
( ) One
( ) Two
( ) Three
3) Example rating between 1-5
(1) (2) (3) (4) (5)
4) Example text response question
___
5) You can do a multi-line textbox too!
___
___
6) Example dropdown question
< > One
< > Two
< > Three
    </textarea><br>
      <button type="submit" class="btn btn-default">Create</button><% end %><br>
    </div>
    <div class="col-md-offset-1 col-md-5 panel panel-info">
      <div class="row panel-heading">Step 2: URLs</div>
      <div class="row panel-body">After your survey has been created. You will be given two URLs.</div>
      <div class="row panel-body"><strong>Public URL:</strong> Share this link with anyone you want to answer your survey.  Be sure to check over your survey first to make sure everything looks okay.
      If anything's wrong, just hit the back button and create another one. </div>
      <div class="row panel-body"><strong>Private URL:</strong> Keep this link private!  It will allow you to download your survey results, see how many people have responded, or close the survey. <u>DO NOT</u> lose this link!  Since Qwk.io is completely anonymous, there's no way to get it back if you lose it.
      </div>
    </div>
  </div>
</div>

app/views/home/legal.html.erb
<div id="main" role="main">
   <div class="centered">
      <div id="admin-survey">
         <div class="survey-link">
            <h1>Legal Mumbo-Jumbo</h1>
            <p>
              Qwk.io is a rapid surveying tool currently operating in beta. That means you should not rely on Qwk.io for hugely
              important surveys, such as elections. Qwk.io makes every effort to operate a reliable, scalable service… but then
              again so does Twitter, and look at them. We may experience planned or unplanned downtime with no notice. We may
              experience programming or administrative errors that produce dubious survey results.
            </p>
            <p>
              Qwk.io reserves the right to remove surveys and/or responses that are offensive, by our sole and possibly capricious
              judgment. Qwk.io further reserves the right to remove or redirect surveys which are promoted by spam or other unsavory
              practices. Qwk.io further further reserves the right to remove any survey or any response for any reason whatsoever.
            </p>
            <p>
              In short: This is a very early product being made available to you solely for the purposes of entertainment and
              testing.  It’s not going to be perfect. And Don’t abuse it.
            </p>
         </div>
      </div>
   </div>
</div>

app/views/home/message.html.erb
<div id="main" role="main">
   <div class="centered">
      <div id="admin-survey">
         <div class="survey-link">
            <h1><%= @header %></h1>
            <p><%= @message %></p>
         </div>
      </div>
   </div>
</div>