config/routes.rb
Rails.application.routes.draw do
  get 'surveys/index'

  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :surveys

  #home pages
  match '/about/' => 'home#about', :via => :get
  match '/help/' => 'home#help', :via => :get
  match '/examples/' => 'home#examples', :via => :get
  match '/legal/' => 'home#legal', :via => :get

  match '/:id' => 'surveys#take', :via => :get, :as => :take
  match '/:id' => 'surveys#respond', :via => :post
  match '/results/:id' => 'surveys#results', via: [:get, :post], :as => :results
  match '/admin/:id/close' => 'surveys#toggle', via: [:get, :post], :as => :closesurvey, :state => true
  match '/admin/:id/unclose' => 'surveys#toggle', via: [:get, :post], :as => :unclosesurvey, :state => false

  root :to => "home#index", :via => :get
end

app/models/survey.rb
class Survey
  include Mongoid::Document

  auto_increment :surveyid, :collection => :surveyid, :seed => 15000
  field :adminkey, :type => String
  field :rawtext, :type => String
  field :closed, :type => Boolean, :default => false

  index({ surveyid: 1 }, { unique: true, name: "surveyid_index" })
  index({ adminkey: 1 }, { unique: true, name: "adminkey_index" })

  validates_presence_of :adminkey

  def responses
    @response_cache || (@response_cache = Response.where(:surveyid => self._id))
  end
end

app/controllers/surveys_controller.rb
require 'uuidtools'

class SurveysController < ApplicationController
  # route for /xxxx (what user will use to take an existing survey)
  def take
    @no_follow = true # If Google finds this link, tell it not to index or follow
    surveyid = params[:id].to_i(36)
    if(surveyid == 0) #bad Base36 number on URL
      render_404
      return
    end

    survey = Survey.where(:surveyid => surveyid).only(:rawtext, :closed)[0]
    if (survey == nil)
      render_404
      return
    end

    @rendering = SurveysHelper::SurveyRender.new(survey)
    @page_title = (@rendering.title || "Unnamed Survey") + " (Qwk.io)"

    #Set Facebook OpenGraph tags so people can post this on their wall
    @og_title = @page_title
    @og_desc = @rendering.description || '' #Do we want some sort of default description here?
    @og_url = "http://qwk.io#{request.fullpath}"

    if(survey.closed?)
      render_closed
      return
    end


    respond_to do |format|
      format.html # take.html.erb
    end
  end


  # route for POST /xxxx (user responds to a survey)
  def respond
    surveyid = params[:id].to_i(36)
    if(surveyid == 0) #bad Base36 number on URL
      render_404
      return
    end

    survey = Survey.where(:surveyid => surveyid).only(:rawtext, :closed)[0]
    if (survey == nil)
      render_404
      return
    end

    if(survey.closed?)
      render_closed
      return
    end

    response = Response.new
    uk = UUIDTools::UUID.timestamp_create.hexdigest.to_s # unique key for this response batch
    response[:surveyid] = survey[:_id]
    response[:userkey] = UUIDTools::UUID.timestamp_create.hexdigest.to_s # unique key for this response batch
    response[:timestamp] = Time.now
    response[:answers] = []

    answers = params[:Q]
    answers.each_key do |a|
      answer = answers[a]
      db_answer = { :question => a.to_i }

      if (answer.class == String) #just record the answer as is
        db_answer[:answer] = answer
      end

      if (answer.respond_to?(:keys)) #convert into a comma delimited list
        db_answer[:answer] = answer.keys.to_a.join(',')
      end

      response[:answers] << db_answer
    end

    # Survey.respond(survey, response)
    response.save

    respond_to do |format|
      format.html
    end
  end

  # POST /surveys
  def create
    @survey = Survey.new
    @ak = UUIDTools::UUID.timestamp_create.to_s

    @survey[:adminkey] = Digest::MD5.digest(@ak).unpack("Q")[0].to_s(36) # 64bit hash for admins
    @survey[:rawtext] = params[:survey]

    #compile this survey to check for errors
    begin
      SurveysHelper::SurveyRender.new(@survey)
    rescue SurveysHelper::NoQuestionsError
      render_badsurvey
      return
    end

    respond_to do |format|
      if @survey.save!
        format.html
      else
        raise 'Could not save survey!' # TODO: Handle error
      end
    end
  end

  def results
    @no_follow = true # If Google finds this link, tell it not to index or follow
    survey = Survey.where(:adminkey => params[:id])[0]
    if (survey == nil)
      render_404
      return
    end

    @rendering = SurveysHelper::SurveyRender.new(survey)
    #We don't store response count in Survey to avoid document locking when user responds, though results page is slightly slower
    @count = Response.where(:surveyid => survey[:_id]).count
    @closed = survey.closed

    respond_to do |format|
      format.html # results.html.erb
      format.csv { render :text => @rendering.to_csv }
      format.json { render :json => @rendering.to_json }
      format.xml { render :xml => @rendering.to_xml }
    end
  end

  def toggle
    @no_follow = true # If Google finds this link, tell it not to index or follow

    Survey.where(:adminkey => params[:id]).update(closed: params[:state]);
    survey = Survey.where(:adminkey => params[:id]).only(:adminkey, :surveyid).limit(1)[0]
    if (survey == nil)
      render_404
      return
    end

    respond_to do |format|
      format.html { redirect_to(results_url(:id => survey.adminkey)) }
      format.json { render :json => { :Closed => params[:state] } }
      format.xml { render :xml => { :Closed => params[:state] } }
    end
  end
end

app/helpers/surveys_helper.rb
require 'json'
require 'csv'
require 'active_model/serializers/xml'

module SurveysHelper
  class NoQuestionsError < RuntimeError
  end

  class SurveyRender
    attr_accessor :survey, :title, :description, :questions

    def initialize(survey)
      @survey = survey
      @title = nil
      @description = nil

      #regular expressions to test what each line is
      @re_question = /^\d*\)(.*)$/
      @re_multichoice = /^\[ \](.*)$/
      @re_radio = /^\( \)(.*)$/
      @re_dropdown = /^\< \>(.*)$/
      @re_textbox = /^_{3,}\s*$/
      @re_pointrating = /^(\(\d+\)\s*){3,10}$/

      compile
    end

    def compile
      @questions = []
      curQuestion = nil
      idx = 0

      @survey.rawtext.each_line do |line|
        line.strip!

        if (line.empty?)
          next
        end

        is_questionheader = @re_question.match(line)
        is_multichoice = @re_multichoice.match(line)
        is_radio = @re_radio.match(line)
        is_dropdown = @re_dropdown.match(line)
        is_textbox = @re_textbox.match(line)
        is_pointrating = @re_pointrating.match(line)

        if (is_questionheader) # line is question header
          curQuestion = {} # start a new question
          curQuestion[:idx] = (idx += 1)

          @questions.push curQuestion
          curQuestion[:title] = is_questionheader.captures[0].strip # title of question
        elsif (is_multichoice && curQuestion) # line is multiple choice checkbox
          curQuestion[:type] ||= 'checkbox'
          curQuestion[:options] ||= []
          curQuestion[:options].push is_multichoice.captures[0]
        elsif (is_radio && curQuestion) # line is radio options
          curQuestion[:type] ||= 'radio'
          curQuestion[:options] ||= []
          curQuestion[:options].push is_radio.captures[0]
        elsif (is_dropdown && curQuestion) # line is dropdown
          curQuestion[:type] ||= 'dropdown'
          curQuestion[:options] ||= []
          curQuestion[:options].push is_dropdown.captures[0]
        elsif (is_textbox && curQuestion) # line is text input box
          if (curQuestion[:type] == 'singleline') # already have a singleline, so let's upgrade it to a multiline
            curQuestion[:type] = 'multiline'
          else
            curQuestion[:type] = 'singleline' unless curQuestion[:type] == 'multiline'
          end
        elsif (is_pointrating && curQuestion) # line is point rating
          curQuestion[:type] = 'pointrating'
          curQuestion[:points] = line.scan('(').count
        elsif (curQuestion && !curQuestion[:type]) #no format match, but we're in a question - make this a question subtext
          curQuestion[:subtitle] = line
        elsif (curQuestion == nil)
          if(@title == nil)
            @title = line
            next
          end

          @description = line
        end
      end

      if (questions.count == 0) # No questions, WTF?
        raise NoQuestionsError
      end
    end

    def to_csv
      map = { }
      @survey.responses.each do |r|
        userkey = r['userkey']
        map[userkey] ||= { :timestamp => r['timestamp'], :answers => Array.new(@questions.length) }
        r['answers'].each do |a|map[userkey][:answers][a['question'] - 1] = a['answer'] end
      end

      #generate csv string
      CSV.generate(headers: true) do |r|
        #build header row
        headers = ["User Key", "Timestamp"]
        @questions.each do |q| headers.push( q[:title]) end
        r << headers

        map.keys.sort_by { |k| map[k][:timestamp] }.each do |user|
          r << [user, map[user][:timestamp]] + map[user][:answers]
        end
      end
    end

    def to_json
      #pivots the responses in the survey
      map = { }
      @survey.responses.each do |r|
        userkey = r['userkey']
        map[userkey] ||= { :timestamp => r['timestamp'], :answers => Array.new(@questions.length) }
        r['answers'].each do |a|map[userkey][:answers][a['question'] - 1] = a['answer'] end
      end

      {
          :responses => map,
          :questions => @questions.collect { |q| { :idx => q[:idx], :title => q[:title] } },
          :title => @title,
          :description => @description
      }.to_json
    end

    def to_xml
      #pivots the responses in the survey
      map = { }
      @survey.responses.each do |r|
        userkey = r['userkey']
        map[userkey] ||= { :timestamp => r['timestamp'], :answers => Array.new(@questions.length), :userkey => r['userkey'] }
        r['answers'].each do |a|map[userkey][:answers][a['question'] - 1] = a['answer'] end
      end

      {
        :responses => map.values.to_a,
        :questions => @questions.collect { |q| { :idx => q[:idx], :title => q[:title] } },
        :title => @title,
        :description => @description
      }.to_xml :root => 'survey'
    end
  end
end

app/views/surveys/create.html.erb
<div class="container">
  <div class="row panel panel-success">
    <div class="panel-heading">Public URL</div>
    <div class="panel-body">
      <input type="textbox" class="js-publicURL URLTextbox" value="<%= take_url(:id => @survey.surveyid.to_s(36)) %>" />
      <button class="btn btn-default js-copyPublicURLbtn">Copy</button>
      <%= link_to 'View Survey', take_url(:id => @survey.surveyid.to_s(36)), :class => 'btn btn-default', :target => '_blank' %>
      <p>Share this link with anyone you want to answer your survey.  Be sure to check over your survey first to make sure everything looks okay. If anything's wrong, just hit the back button and create another one.  Remember, you won't have to pay until you want to actually download the results of a survey.</p>
    </div>
  </div>
  <div class="row panel panel-info">
    <div class="panel-heading">Private URL</div>
    <div class="panel-body">
      <input type="textbox" class="js-privateURL URLTextbox" value="<%= results_url(:id => @survey.adminkey) %>" />
      <button class="btn btn-default js-copyPrivateURLbtn">Copy</button>
      <%= link_to 'Download Results', results_url(:id => @survey.adminkey), :class => 'btn btn-default', :target => '_blank' %>
      <p>Keep this link private!  It will allow you to download your survey results, see how many people have responded, or close the survey.<u>DO NOT</u> lose this link!  Since Qwk.io is completely anonymous, there's no way to get it back if you lose it.</p>
    </div>
  </div>
</div>
<script>
var copyPublicURLbtn = document.querySelector('.js-copyPublicURLbtn');
copyPublicURLbtn.addEventListener('click', function(event){
  var copyPublicURL = document.querySelector('.js-publicURL');
  copyPublicURL.select();
  var successful = document.execCommand('copy');
});

var copyPrivateURLbtn = document.querySelector('.js-copyPrivateURLbtn');
copyPrivateURLbtn.addEventListener('click', function(event){
  var copyPrivateURL = document.querySelector('.js-privateURL');
  copyPrivateURL.select();
  document.execCommand('copy');
});
</script>

app/views/surveys/respond.html.erb
<div id="main" role="main">
   <div class="centered">
      <div id="complete">
         <h2> Thank you for participating!</h2>
         <div class="survey-link">
            <h3>About Qwk.io</h3>
            <p>Qwk.io is the fastest &amp; easiest way to create and distribute surveys. Creating a survey takes minutes and you can get unlimited responses for just $1. No subscriptions, no rebilling, no hassle.</p>
            <h3><a href="/">Create your own survey!</a></h3>
         </div>
      </div>
   </div>
</div>

app/views/surveys/results.html.erb
<div class="container">
   <div class="row">
      <div class="panel panel-info">
         <div class="panel-heading"> <%= @rendering.title %> (<%= @count %> <%= @count == 1 ? 'Result' : 'Results' %>)</div>
         <div class="panel-body">
            <h1>Download Results</h1>
            <div>
               <%= link_to 'CSV (Excel)', request.fullpath + '.csv', :class => 'btn btn-default' %>
               <%= link_to 'XML', request.fullpath + '.xml', :class => 'btn btn-default' %>
               <%= link_to 'JSON', request.fullpath + '.json', :class => 'btn btn-default' %>
            </div>
            <p> Click one of the links above to download the results of your survey.  CSV (comma-separated values) format should work
               with most major spreadsheet applications such as Microsoft Excel.  The XML and JSON formats might be useful for accessing
               survey results programmatically.</p>
         </div>
         <div class="panel-body">
           <h1>Open/Close Survey</h1>
            <% if (@closed) %>
                <%= link_to 'Re-Open Survey', unclosesurvey_url(:id => params[:id]), :class => 'btn btn-default' %>
                <p>
                  This survey is currently closed.  Click the link above to re-open it.
                </p>
            <% else %>
                 <%= link_to 'Close Survey', closesurvey_url(:id => params[:id]), :class => 'btn btn-default' %>
               <p>
                 When you close your survey, anyone who visits your survey's public URL will get an error message saying the survey has been
                 closed.  You will still be able to access the survey results even after you close a survey.  Don't worry if you close a
                 survey by mistake, you can always re-open it again.
               </p>
            <% end %>
         </div>
      </div>
   </div>
</div>

app/views/surveys/take.html.erb
<div class="container survey">
  <div class="row panel panel-success">
     <div class="panel-heading"><%= @rendering.title %></div>
     <div class="panel-body"><%= @rendering.description %></div>
     <%= form_tag(request.fullpath) do %>
        <ol>
           <% @rendering.questions.each do |q| %>
              <li>
                 <%= q[:title] %>
                 <% if q[:type] == 'radio' %>
                   <% i = 0 %>
                   <% q[:options].each do |option| %>
                     <div class="radio">
                        <input name="Q[<%= q[:idx] %>]" id="Q_<%= q[:idx] %>_R<%= (i += 1) %>" type="radio" value="<%= i %>" />
                        <label for="Q_<%= q[:idx] %>_R<%= i %>"><%= option %></label>
                     </div>
                   <% end %>
                 <% end %>

                 <% if q[:type] == 'pointrating' %>
                     <div class="radio">
                     <% q[:points].times do |i| %>
                       <div class="q-ratio">
                         <input name="Q[<%= q[:idx] %>]" value="<%= i + 1 %>" id="Q_<%= q[:idx] %>_R<%= i %>" type="radio" />
                         <label for="Q_<%= q[:idx] %>_R<%= i %>"><%= i + 1 %></label>
                       </div>
                     <% end %>
                     </div>
                 <% end %>

                <% if q[:type] == 'checkbox' %>
                    <div class="checkbox">
                      <% i = 0 %>
                      <% q[:options].each do |option| %>
                        <div class="checkbox">
                          <input name="Q[<%= q[:idx] %>][<%= (i += 1) %>]" id="Q_<%= q[:idx] %>_CB<%= i %>" type="checkbox" />
                          <label for="Q_<%= q[:idx] %>_CB<%= i %>"><%= option %></label>
                        </div>
                      <% end %>
                    </div>
                <% end %>

                <% if q[:type] == 'dropdown' %>
                  <div>
                   <select name="Q[<%= q[:idx] %>]">
                     <% i = 0 %>
                     <% q[:options].each do |option| %>
                       <option value="<%= (i += 1) %>"><%= option %></option>
                     <% end %>
                   </select>
                  </div>
                <% end %>

                <% if q[:type] == 'singleline' %>
                   <div>
                      <input type="textbox" name="Q[<%= q[:idx] %>]" />
                   </div>
                <% end %>

                <% if q[:type] == 'multiline' %>
                   <div>
                      <textarea name="Q[<%= q[:idx] %>]" rows="5"></textarea>
                   </div>
                <% end %>
              </li>
           <% end %>
        </ol>
        <div class="panel-body">
           <input type="submit" class="btn btn-default" name="public-submit" value="Submit"/>
        </div>
     <% end %>
  </div>
</div>